### ISSUE TITLE
Create a proper GitHub App?

### ISSUE THREAD

**Issue by julienrf** [scala-steward-org/scala-steward-action#392]
(This is more a question than an issue)

Currently, the setup instructions tell you to create either a GitHub App or a personal GitHub token. When using a personal token, Scala Steward submits pull requests on behalf of your account, which is not great. This issue is solved with the GitHub App approach, however that approach is a bit cumbersome (the users have to follow the full process for creating the app and store the private key somewhere to be able to reuse it on every repository they want to apply the action to).

It seems possible to create a “global” Scala Steward app that everyone could install on their repositories. With this approach, the users would not have to create tokens or apps, they would only install the app on their repositories, and then create a workflow that uses it, and the workflow would submit the PRs on behalf of the app. This is for instance what is done in this example app: https://github.com/probot/example-github-action/issues/1#issuecomment-743591056. The comment has been posted by the workflow, on behalf of the “github-actions” app.

Would you be interested in giving a try to this approach?

**Comment by alejandrohdezma** [comment]
Hey @julienrf, that would be a different approach than the purpose of this repository, which is running Scala Steward yourself. If a "global" Scala Steward would be created, the actual running of the program would have to be centralized, since in order to retrieve the list of repositories for an installation, an app needs to be authenticated (for which you need its private key). An alternative to this will be using [the public instance managed by VirtusLab](https://github.com/scala-steward-org/scala-steward#quick-start-guide).

**Comment by julienrf** [comment]
I see. I thought there would be a way to run Scala Steward ourselves but still post comments on behalf of a “global” app, but after digging more that seems complicated (at some point we need to provide the private key of the global app to the users…)
