### ISSUE TITLE
buildRoots not work on monorepo

### ISSUE THREAD

**Issue by letusfly85** [scala-steward-org/scala-steward-action#399]
Thank you for great github actions.

Today, I have a question.

I set the following structure on a private repository.
But the sweawrd doesn't update any dependencies.
How can I fix..?

```bash
.github/.scala-steward.conf
.github/workflows/steward.yml

backend/build.sbt
backend/project/plugins.sbt
frontend/package.json
```

```bash
cat .github/.scala-steward.conf

buildRoots = [ "../backend" ]
```

```bash
cat .github/workflows/steward.yml

name: Dependency Check Backend

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKENS }}
```

---

Even if I changed like below, the actions doesn't update any dependencies.

```bash
cat .github/.scala-steward.conf

buildRoots = [ "backend" ]
```

Should I set `build.sbt` on the root directory of my repository?

**Comment by alejandrohdezma** [comment]
Hey @letusfly85, the `.scala-steward.conf` file must be on the repository root directory (instead of `.github`).

**Comment by letusfly85** [comment]
@alejandrohdezma 

Thank you!

Finally, I fixed, by changing the `.scala-steward.conf` to the root directly 👍🏻 

But why this repository README.md explains that the default position is `.github/.scala-steward.conf` 😅  ?

**Comment by alejandrohdezma** [comment]
I guess you're talking about the `repo-config` input, that's for providing a base configuration when updating multiple repositories (it could also be used in your case though) but in order to use it one must `checkout` the repository first, so the action can find the file. By adding the `.scala-steward.conf` file directly in your repo, you're providing [this](https://github.com/scala-steward-org/scala-steward/blob/main/docs/repo-specific-configuration.md), while by adding it to `.github` you're providing the [`--repo-config` argument for Scala Steward](https://github.com/scala-steward-org/scala-steward/blob/main/docs/help.md).

**Comment by letusfly85** [comment]
@alejandrohdezma 

Thank you!

I understand exactly 👍🏻 

I will close this issue.
