### ISSUE TITLE
Support overriding default "--cache-ttl 2hours"

### ISSUE THREAD

**Issue by MPV** [scala-steward-org/scala-steward-action#62]
As mentioned in https://github.com/scala-steward-org/scala-steward-action/issues/52#issuecomment-640791193, there's a cache TTL that we could support overriding:

(now that we're using it's cache, after #59)

> Scala Steward has a `--cache-ttl` option that controls how often it checks for new versions. The default value is `2hours`.

**Comment by alejandrohdezma** [comment]
Leaving this here as a description of what should be done to develop this feature, since it is simple enough to mark it as `good-first-issue`:

- Add a new input in [`action.yml`](https://github.com/scala-steward-org/scala-steward-action/blob/master/action.yml) file called `cache-ttl` with a default value of `'2hours'` and `required: false`.
- Recover this new input in [`main.ts`](https://github.com/scala-steward-org/scala-steward-action/blob/master/src/main.ts) with `const cacheTTL = core.getInput('cache-ttl')`.
- Add it to the [list of scala-steward arguments](https://github.com/scala-steward-org/scala-steward-action/blob/064a2e2d3ca25870c2a2ad18afdd749a5a986ab0/src/main.ts#L35-L48) at the bottom of the `run` function in `main.ts` like: `['--cache-ttl', cacheTTL],

**Comment by alejandrohdezma** [comment]
Implemented in #151
